steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--build-arg', 'BASE_IMAGE=us-central1-docker.pkg.dev/votos-app-99/odoo/odoo19-enterprise:v1',
      '-t', 'us-central1-docker.pkg.dev/votos-app-99/odoo/odoo19-custom:latest',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/votos-app-99/odoo/odoo19-custom:latest']

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/odoo-app'
      - 'odoo=us-central1-docker.pkg.dev/votos-app-99/odoo/odoo19-custom:latest'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=odoo-cluster'